version: '3'

services:
  node_app:
    container_name: node_app
    restart: unless-stopped
    build: ./
    ports:
      - 4000:4000
    networks:
      - full_app
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - full_app

networks:
  full_app:
    driver: bridge

volumes:
  mongo-data:
    driver: local